export const ADMIN_PAGE = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>定时任务助手</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f6f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1220px;margin:0 auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:18px}.title{font-size:28px;font-weight:760}.sub{color:#687386;font-size:13px;margin-top:4px}.tabs{display:flex;gap:8px;margin:18px 0}.tab,button{border:1px solid #d9deea;background:#fff;border-radius:10px;padding:9px 13px;cursor:pointer}.tab.active{background:#172033;color:#fff;border-color:#172033}.primary{background:#1769e0;color:#fff;border-color:#1769e0}.danger{color:#c43030}.muted{color:#7b8496}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.card{background:#fff;border:1px solid #e4e7ef;border-radius:14px;padding:16px}.stat{font-size:25px;font-weight:750;margin-top:8px}.panel{background:#fff;border:1px solid #e4e7ef;border-radius:14px;overflow:hidden}.panelhead{padding:15px 16px;border-bottom:1px solid #edf0f5;display:flex;justify-content:space-between;align-items:center}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:900px}th,td{text-align:left;padding:12px 14px;border-bottom:1px solid #edf0f5;font-size:13px;vertical-align:top}th{color:#657085;font-weight:650;background:#fafbfc}.badge{display:inline-flex;border-radius:999px;padding:3px 8px;font-size:12px;background:#eef2f8}.badge.active,.badge.succeeded{background:#e7f7ef;color:#177448}.badge.paused{background:#fff4d9;color:#8c6500}.badge.failed{background:#fdeaea;color:#a62f2f}.actions{display:flex;flex-wrap:wrap;gap:6px}.actions button{padding:5px 8px;font-size:12px}.empty{padding:35px;text-align:center;color:#8a93a3}.modal{display:none;position:fixed;inset:0;background:#0006;z-index:10;align-items:flex-start;justify-content:center;padding:6vh 16px;overflow:auto}.modal.open{display:flex}.dialog{width:min(760px,100%);background:#fff;border-radius:16px;padding:20px;box-shadow:0 20px 60px #0003}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{margin:12px 0}.field label{display:block;font-size:12px;color:#657085;margin-bottom:6px}input,select,textarea{width:100%;border:1px solid #d9deea;border-radius:9px;padding:9px 10px;font:inherit}textarea{min-height:135px;resize:vertical}.foot{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.notice{padding:10px 12px;border-radius:9px;background:#eef5ff;color:#265b9b;font-size:13px;margin-bottom:12px}.error{background:#fdeaea;color:#a62f2f}.hidden{display:none}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.row{grid-template-columns:1fr}.wrap{padding:14px}.title{font-size:23px}}
</style>
</head>
<body><div class="wrap">
<div class="top"><div><div class="title">定时任务助手</div><div class="sub">Cloudflare Worker · Remote MCP · Durable Objects SQLite</div></div><button class="primary" onclick="openTask()">新增任务</button></div>
<div id="notice" class="notice hidden"></div>
<div class="grid"><div class="card">任务总数<div id="sTotal" class="stat">-</div></div><div class="card">运行中<div id="sActive" class="stat">-</div></div><div class="card">已暂停<div id="sPaused" class="stat">-</div></div><div class="card">执行记录<div id="sRuns" class="stat">-</div></div></div>
<div class="tabs"><button id="tabTasks" class="tab active" onclick="showTab('tasks')">任务列表</button><button id="tabRuns" class="tab" onclick="showTab('runs')">执行明细</button></div>
<section id="tasksPanel" class="panel"><div class="panelhead"><b>任务列表</b><button onclick="loadAll()">刷新</button></div><div class="tablewrap"><table><thead><tr><th>任务</th><th>状态</th><th>调度</th><th>下次执行</th><th>通知</th><th>附件</th><th>操作</th></tr></thead><tbody id="taskRows"></tbody></table></div></section>
<section id="runsPanel" class="panel hidden"><div class="panelhead"><b>执行明细</b><button onclick="loadRuns()">刷新</button></div><div class="tablewrap"><table><thead><tr><th>时间</th><th>任务</th><th>状态</th><th>尝试</th><th>执行结果</th><th>通知结果</th></tr></thead><tbody id="runRows"></tbody></table></div></section>
</div>
<div id="taskModal" class="modal"><div class="dialog"><h3 id="formTitle">新增任务</h3><form id="taskForm" onsubmit="saveTask(event)"><input id="fId" type="hidden" />
<div class="field"><label>任务名称</label><input id="fTitle" required maxlength="200" /></div>
<div class="field"><label>交给 ChatGPT 执行的完整指令</label><textarea id="fInstruction" required></textarea></div>
<div class="row"><div class="field"><label>调度类型</label><select id="fKind" onchange="syncScheduleFields()"><option value="once">单次</option><option value="interval">固定间隔</option><option value="cron">Cron</option></select></div><div class="field"><label>时区</label><input id="fTimezone" value="Asia/Shanghai" /></div></div>
<div id="onceFields" class="field"><label>执行时间</label><input id="fAt" type="datetime-local" /></div>
<div id="intervalFields" class="field hidden"><label>每隔多少分钟</label><input id="fEvery" type="number" min="1" value="60" /></div>
<div id="cronFields" class="field hidden"><label>Cron 表达式</label><input id="fCron" placeholder="0 8 * * *" /></div>
<div class="row"><div class="field"><label>通知渠道（可多选，逗号分隔）</label><input id="fChannels" value="chatgpt" placeholder="chatgpt,weixin,email,ntfy" /></div><div class="field"><label>通知条件</label><select id="fNotifyOn"><option value="always">无论成功失败</option><option value="success">仅成功</option><option value="failure">仅失败</option></select></div></div>
<div class="row"><div class="field"><label>微信 recipients（逗号分隔）</label><input id="fWeixin" /></div><div class="field"><label>邮件地址（逗号分隔）</label><input id="fEmail" /></div></div><div class="field"><label>ntfy topic</label><input id="fNtfy" /></div>
<div class="field"><label>添加附件（单个 ≤ 10 MiB，可保存多个）</label><input id="fFile" type="file" multiple /></div>
<div class="foot"><button type="button" onclick="closeTask()">取消</button><button class="primary" type="submit">保存</button></div></form></div></div>
<script>
let tasks=[];let runs=[];
const el=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{'content-type':'application/json',...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||('HTTP '+r.status));return d}
function note(msg,bad=false){const n=el('notice');n.textContent=msg;n.className='notice'+(bad?' error':'');setTimeout(()=>n.classList.add('hidden'),5000)}
function fmt(t){if(!t)return '-';try{return new Date(t).toLocaleString()}catch{return t}}
function sched(s){if(!s)return '-';if(s.kind==='once')return '单次 '+fmt(s.at);if(s.kind==='interval')return '每 '+s.everyMinutes+' 分钟';return 'Cron '+s.expression+' ('+(s.timezone||'')+')'}
async function loadAll(){try{const [st,td]=await Promise.all([api('/admin/api/status'),api('/admin/api/tasks')]);tasks=td.tasks||[];el('sTotal').textContent=st.tasks.total;el('sActive').textContent=st.tasks.active;el('sPaused').textContent=st.tasks.paused;el('sRuns').textContent=st.runs.total;renderTasks()}catch(e){note(e.message,true)}}
function renderTasks(){el('taskRows').innerHTML=tasks.length?tasks.map(t=>'<tr><td><b>'+esc(t.title)+'</b><div class="muted">'+esc(t.id)+'</div></td><td><span class="badge '+esc(t.status)+'">'+esc(t.status)+'</span></td><td>'+esc(sched(t.schedule))+'</td><td>'+esc(fmt(t.nextDueAt))+'</td><td>'+esc((t.notification?.channels||[]).join(', '))+'</td><td>'+esc(t.attachmentCount||0)+'</td><td><div class="actions"><button onclick="editTask(\''+esc(t.id)+'\')">编辑</button>'+(t.status==='paused'?'<button onclick="act(\''+esc(t.id)+'\',\'resume\')">恢复</button>':'<button onclick="act(\''+esc(t.id)+'\',\'pause\')">暂停</button>')+'<button onclick="act(\''+esc(t.id)+'\',\'trigger\')">立即触发</button><button onclick="showAttachments(\''+esc(t.id)+'\')">附件</button><button class="danger" onclick="delTask(\''+esc(t.id)+'\')">删除</button></div></td></tr>').join(''):'<tr><td colspan="7" class="empty">暂无任务</td></tr>'}
async function loadRuns(){try{const d=await api('/admin/api/runs?limit=200');runs=d.runs||[];renderRuns()}catch(e){note(e.message,true)}}
function renderRuns(){el('runRows').innerHTML=runs.length?runs.map(r=>'<tr><td>'+esc(fmt(r.createdAt))+'</td><td>'+esc(r.taskId)+'</td><td><span class="badge '+esc(r.status)+'">'+esc(r.status)+'</span></td><td>'+esc(r.attempt)+'</td><td style="max-width:360px;white-space:pre-wrap">'+esc(r.resultText||r.errorText||'-')+'</td><td style="max-width:280px;white-space:pre-wrap">'+esc(JSON.stringify(r.notificationResults||[]))+'</td></tr>').join(''):'<tr><td colspan="6" class="empty">暂无执行记录</td></tr>'}
function showTab(t){el('tasksPanel').classList.toggle('hidden',t!=='tasks');el('runsPanel').classList.toggle('hidden',t!=='runs');el('tabTasks').classList.toggle('active',t==='tasks');el('tabRuns').classList.toggle('active',t==='runs');if(t==='runs')loadRuns()}
function syncScheduleFields(){const k=el('fKind').value;el('onceFields').classList.toggle('hidden',k!=='once');el('intervalFields').classList.toggle('hidden',k!=='interval');el('cronFields').classList.toggle('hidden',k!=='cron')}
function openTask(t){el('taskForm').reset();el('fId').value=t?.id||'';el('formTitle').textContent=t?'编辑任务':'新增任务';el('fTitle').value=t?.title||'';el('fInstruction').value=t?.instruction||'';el('fKind').value=t?.schedule?.kind||'once';el('fTimezone').value=t?.schedule?.timezone||'Asia/Shanghai';if(t?.schedule?.at)el('fAt').value=new Date(t.schedule.at).toISOString().slice(0,16);el('fEvery').value=t?.schedule?.everyMinutes||60;el('fCron').value=t?.schedule?.expression||'';el('fChannels').value=(t?.notification?.channels||['chatgpt']).join(',');el('fNotifyOn').value=t?.notification?.notifyOn||'always';el('fWeixin').value=(t?.notification?.weixinRecipients||[]).join(',');el('fEmail').value=(t?.notification?.emailTo||[]).join(',');el('fNtfy').value=t?.notification?.ntfyTopic||'';syncScheduleFields();el('taskModal').classList.add('open')}
function closeTask(){el('taskModal').classList.remove('open')}
function editTask(id){openTask(tasks.find(t=>t.id===id))}
const csv=v=>v.split(',').map(s=>s.trim()).filter(Boolean);
async function saveTask(e){e.preventDefault();try{const kind=el('fKind').value;let schedule={kind,timezone:el('fTimezone').value.trim()||'Asia/Shanghai'};if(kind==='once')schedule.at=new Date(el('fAt').value).toISOString();if(kind==='interval')schedule.everyMinutes=Number(el('fEvery').value);if(kind==='cron')schedule.expression=el('fCron').value.trim();const id=el('fId').value;const body={...(id?{id}:{}),title:el('fTitle').value,instruction:el('fInstruction').value,schedule,notification:{channels:csv(el('fChannels').value),notifyOn:el('fNotifyOn').value,weixinRecipients:csv(el('fWeixin').value),emailTo:csv(el('fEmail').value),ntfyTopic:el('fNtfy').value.trim()}};const d=await api('/admin/api/tasks/'+(id?'update':'create'),{method:'POST',body:JSON.stringify(body)});const taskId=d.task.id;for(const file of el('fFile').files){if(file.size>10*1024*1024)throw new Error(file.name+' 超过 10 MiB');const dataBase64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});await api('/admin/api/attachments/add',{method:'POST',body:JSON.stringify({taskId,fileName:file.name,mimeType:file.type||'application/octet-stream',dataBase64})})}closeTask();note('已保存');await loadAll()}catch(e){note(e.message,true)}}
async function act(id,a){try{await api('/admin/api/tasks/'+a,{method:'POST',body:JSON.stringify({id})});await loadAll()}catch(e){note(e.message,true)}}
async function delTask(id){if(!confirm('删除任务及其执行明细和附件？'))return;try{await api('/admin/api/tasks/delete',{method:'POST',body:JSON.stringify({id})});await loadAll()}catch(e){note(e.message,true)}}
async function showAttachments(id){try{const d=await api('/admin/api/tasks/'+encodeURIComponent(id));const t=d.task;const refs=await api('/admin/api/attachments?taskId='+encodeURIComponent(id));const list=refs.attachments||[];if(!list.length){alert('此任务暂无附件');return}const text=list.map(a=>a.fileName+'\n'+location.origin+'/admin/attachment/'+encodeURIComponent(a.attachmentRef)).join('\n\n');alert(text)}catch(e){note(e.message,true)}}
el('taskModal').addEventListener('click',e=>{if(e.target===el('taskModal'))closeTask()});loadAll();
</script></body></html>`;
